blog/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^index-(?P<label_id>\S+)-(?P<key_words>\S+)-(?P<page_id>\d+)', views.index, name='index'),
    path('detail/<slug:pk>', views.DetailView.as_view(), name='detail'),
]

blogs/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('a/', admin.site.urls),
    path('', include('blog.urls')),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
]

blog/models.py
import uuid

from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# models.py是Web应用数据库的定义文件, 以Python类的形式定义数据库中的各个表.
# Create your models here.


# 状态: 草稿, 发布, 删除
class Status(models.Model):
    # 主键使用UUID, 这里的default使用的是uuid.uuid4而不是uuid.uuid4(),uuid.uuid4()为函数的返回值, 只调用一次,
    # 以后新建函数都用第一次返回的值, 而uuid.uuid4为函数, 每次新建对象都会调用一次函数
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # 名称
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


# 标签
class Label(models.Model):
    # 主键使用UUID
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # 名称
    name = models.CharField(max_length=30)
    # 博客数量
    count = models.IntegerField(default=0, editable=False)

    def __str__(self):
        return self.name


# 博客
class Blog(models.Model):
    # 主键使用UUID
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # 标题
    title = models.CharField(max_length=50)
    # 内容
    content = RichTextUploadingField(null=True, blank=True)
    # 所属标签, 不直接级联删除, 若有子节点, 抛出ProtectedError异常
    label = models.ManyToManyField(Label)
    # 状态, 不直接级联删除, 若有子节点, 抛出ProtectedError异常
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    # 修改时间
    modify_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
# Create your views here.
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.db.models import Q

from .models import Blog, Label


def home(request):
    return HttpResponseRedirect(reverse('blog:index', args=('0', 'noKeyWords', 1)))


def index(request, *args, **kwargs):
    label_list = Label.objects.all()
    # 获得参数
    global blog_list
    label_id = kwargs.get('label_id')
    key_words = kwargs.get('key_words')
    page_id = int(kwargs.get('page_id'))

    # 根据条件查询博客
    if label_id != '0' and key_words != 'noKeyWords':
        blog_list = Blog.objects.filter(
            Q(status__name='发布', label=label_id, title__contains=key_words) |
            Q(status__name='发布', label=label_id, content__contains=key_words) |
            Q(status__name='发布', label=label_id, label__name__contains=key_words)).distinct().order_by('-modify_date')
    if label_id != '0' and key_words == 'noKeyWords':
        blog_list = Blog.objects.filter(Q(status__name='发布', label=label_id)).distinct().order_by('-modify_date')
    if label_id == '0' and key_words != 'noKeyWords':
        blog_list = Blog.objects.filter(
            Q(status__name='发布', title__contains=key_words) |
            Q(status__name='发布', content__contains=key_words) |
            Q(status__name='发布', label__name__contains=key_words)).distinct().order_by('-modify_date')
    if label_id == '0' and key_words == 'noKeyWords':
        blog_list = Blog.objects.filter(Q(status__name='发布')).distinct().order_by('-modify_date')

    # 创建分页对象
    paginator = Paginator(blog_list, 10)
    # 根据当前页码,确定返回的数据
    current_page = paginator.page(page_id)
    return render(request, 'blog/index.html', locals())


class DetailView(generic.DetailView):
    model = Blog
    template_name = 'blog/detail.html'

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="https://paulandcode.com/develop/ico/favicon.ico">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/prism.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/front.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'ckeditor/ckeditor/contents.css' %}">
    <script src="{% static 'blog/js/front.js' %}"></script>
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <title>黄建峰的个人博客</title>
</head>

<body style="background-color: rgb(47, 80, 85)">
<div id="base_header">
</div>
<div id="base_body">
    {% block body %}{% endblock %}
    <div id="base_home">
        <button class="blackButton" onclick="goHome()"><img src="https://paulandcode.com/develop/img/home.png"></button>
    </div>
</div>
<div id="base_footer">
    Powered by: <a target="_blank" href="https://www.djangoproject.com">Django</a>&nbsp;&nbsp;&nbsp;
    GitHub: <a target="_blank" href="https://github.com/paulandcode">paulandcode</a><br>
    ©2017-2018&nbsp;&nbsp;&nbsp;<a target="_blank" href="http://www.beian.miit.gov.cn">津ICP备18001706号</a>
</div>
</body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block body %}
    <div id="detail_body">
        <h1 id="detail_title">{{ blog.title }}</h1>
        <div id="detail_label">
            {% for label in blog.label.all %}
                <label id="label{{ forloop.counter }}" onclick="location.href='{% url 'blog:index' label.id 'noKeyWords' 1%}'">
                    {{ label.name }}
                </label>&nbsp;&nbsp;&nbsp;
            {% endfor %}
        </div>
        <br/><br/>
        <div class="cke_editable cke_editable_themed cke_contents_ltr cke_show_borders">
            {{ blog.content|safe }}
        </div>
        <div id="detail_back">
            <button class="blackButton" onclick="returnBack()"><img src="https://paulandcode.com/develop/img/back.png"></button>
        </div>
        <div id="detail_up">
            <button class="blackButton" onclick="returnTop()"><img src="https://paulandcode.com/develop/img/up.png"></button>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block body %}
    <div id="labels">
        {% if label_list %}
            {% for label in label_list %}
                <label class="subLabel" onclick="location.href='{% url 'blog:index' label.id 'noKeyWords' 1%}'">
                    {{ label.name }}
                </label>&nbsp;&nbsp;&nbsp;
            {% endfor %}
        {% endif %}
    </div>
    <div id="indexSearch">
        <input id="searchText" type="text" title="" value="">&nbsp;&nbsp;&nbsp;
        <button id="searchButton" onclick="
                var finalUrl = '{% url 'blog:index' '0' 'value' 1 %}';
                var value = document.getElementById('searchText').value;
                if (value === '') {
                value = 'noKeyWords';
                }
                finalUrl = finalUrl.replace('value',value);
                location.href = finalUrl;">Search
        </button>
    </div>
    <div class="page">
        <div class="page_list">
            {% if current_page %}
                {% for blog in current_page %}
                    <div class="blogTitle" onclick="location.href='{% url 'blog:detail' blog.id %}'">
                        {{ blog.title }}
                        <br>
                        <span class="blogDate">{{ blog.modify_date }}</span>
                    </div><br>
                {% endfor %}
            {% else %}
                <p>No blogs are available.</p>
            {% endif %}
        </div>
        <div class="page_num">
            {# 判断'上一页'是否存在,如果存在则保留`上一页`标签 ,反之则不显示`上一页`标签 #}
            {% if current_page.has_previous %}
                <a href="{% url 'blog:index' label_id key_words current_page.previous_page_number %}"
                   rel="external nofollow">上一页</a>
            {% endif %}
            {# 确定分页数量 #}
            {% for index in paginator.page_range %}
                {# 如果页码与当前页面相符,则添加红色背景 #}
                {% if page_id == index %}
                    <a href="{% url 'blog:index' label_id key_words index %}"
                       style="background-color: rgb(0, 0, 0);">{{ index }}</a>
                    {# 如果页面与当前页面不符,则正常显示 #}
                {% else %}
                    <a href="{% url 'blog:index' label_id key_words index %}" rel="external nofollow">{{ index }}</a>
                {% endif %}
            {% endfor %}
            {# 判断'下一页'是否存在,如果存在则保留`下一页`标签 ,反之则不显示`下一页`标签 #}
            {% if current_page.has_next %}
                <a href="{% url 'blog:index' label_id key_words current_page.next_page_number %}"
                   rel="external nofollow">下一页</a>
            {% endif %}
        </div>
    </div>
{% endblock %}